language: php
php:
  - 7.1.6
script:
  - php -f src/vfetc.php files=data/vendor/agilent/example_batch1.txt,data/vendor/agilent/example_batch2.txt outputfile=data/tmp/agilent.txt
  - php -f src/vfetc.php files=data/vendor/sciex/example_batch1.txt outputfile=data/tmp/sciex.txt
  - php -f src/vfetc.php files=data/vendor/shimadzu/example_batch1.txt,data/vendor/shimadzu/example_batch2.txt,data/vendor/shimadzu/example_batch3.txt outputfile=data/tmp/shimadzu.txt
  - php -f src/vfetc.php files=data/vendor/waters/example_batch1.txt,data/vendor/waters/example_batch2.txt outputfile=data/tmp/waters.txt

